apiVersion: apps/v1
kind: Deployment
metadata:
  name: maas-api
spec:
  template:
    spec:
      containers:
      - name: maas-api
        env:
        - name: PROVIDER
          value: "sa-tokens"
