apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: maas-production-deployment

# Full production deployment
resources:
- ../../core-infrastructure
- ../kustomize-templates/models/simulator
- ../kustomize-templates/auth/api-keys
- ../kustomize-templates/auth/token-rate-limiting
- ../kustomize-templates/observability
- routes.yaml