apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: maas-kubernetes-overlay

# Base configuration
resources:
- ../../examples/gpu-deployment

# Kubernetes Ingress (for non-OpenShift clusters)
- ingress.yaml