apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: keycloak-oidc-auth
  annotations:
    config.kubernetes.io/local-config: "true"

namespace: keycloak-system

resources:
  - 01-keycloak-namespace.yaml
  - 02-keycloak-deployment.yaml
  - 03-maas-realm-config.yaml
  - 04-realm-import-job.yaml
  - 05-auth-policy-oidc.yaml
  - 06-rate-limit-policy-oidc.yaml

labels:
  - pairs:
      app.kubernetes.io/name: keycloak
      app.kubernetes.io/part-of: maas-auth
      app.kubernetes.io/managed-by: kustomize

commonAnnotations:
  config.kubernetes.io/origin: |
    path: deployment/kuadrant/keycloak/kustomization.yaml
