# Gateway API Gateway for Kuadrant
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: inference-gateway
  namespace: llm
spec:
  gatewayClassName: istio
  listeners:
    - name: http
      hostname: "*.maas.local"
      port: 80
      protocol: HTTP