apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- 00-platform-services-namespace.yaml
- 01-rbac.yaml
- 02-key-manager-deployment.yaml
- 03-auth-policy.yaml
- 04-token-rate-limit-policy.yaml
- 05-external-access.yaml
- 06-admin-secret.yaml
- 07-key-manager-routing.yaml
- 08-reference-grant.yaml
- 09-key-manager-route.yaml
- 10-key-manager-auth-override.yaml
