apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: maas-api

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - httproute.yaml
  - auth-override.yaml
  - tier-mapping-configmap.yaml
  - clusterrolebinding.yaml
  - clusterrole.yaml
