# KServe Configuration for Kuadrant Integration on OpenShift
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: inferenceservice-config
  namespace: kserve
data:
  deploy: |
    {
      "defaultDeploymentMode": "RawDeployment"
    }
  ingress: |
    {
      "enableGatewayApi": true,
      "kserveIngressGateway": "llm/inference-gateway",
      "ingressGateway": "istio-system/istio-ingressgateway",
      "ingressDomain": "apps.summit-gpu.octo-emerging.redhataicoe.com"
    }
  storageInitializer: |
    {
      "image": "kserve/storage-initializer:v0.15.2",
      "memoryRequest": "500Mi",
      "memoryLimit": "4Gi",
      "cpuRequest": "200m",
      "cpuLimit": "1"
    }
  logger: |
    {
      "image": "kserve/agent:v0.15.2",
      "memoryRequest": "100Mi",
      "memoryLimit": "1Gi",
      "cpuRequest": "100m",
      "cpuLimit": "1"
    }
  batcher: |
    {
      "image": "kserve/agent:v0.15.2",
      "memoryRequest": "100Mi",
      "memoryLimit": "1Gi",
      "cpuRequest": "100m",
      "cpuLimit": "1"
    }
  agent: |
    {
      "image": "kserve/agent:v0.15.2",
      "memoryRequest": "100Mi",
      "memoryLimit": "1Gi",
      "cpuRequest": "100m",
      "cpuLimit": "1"
    }
